# Generated by Django 4.2.11 on 2024-04-30 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='price_per_1000',
        ),
    ]
