# Generated by Django 4.2.11 on 2024-05-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_service_guide_prompt_alter_service_price_per_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='link',
            field=models.CharField(default='', max_length=235),
        ),
    ]
