# Generated by Django 4.2.11 on 2024-05-04 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('keywords', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('entities', models.ManyToManyField(blank=True, to='app.entities')),
                ('intent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.intent')),
            ],
        ),
        migrations.AddField(
            model_name='entities',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.intent'),
        ),
    ]
