# Generated by Django 4.2.11 on 2024-05-04 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_entities_intent_usermessage_entities_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='entities',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='intent',
        ),
        migrations.DeleteModel(
            name='Entities',
        ),
        migrations.DeleteModel(
            name='Intent',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
